### ISSUE TITLE
Custom dialog styling

### ISSUE THREAD

**Issue by ahabbaba9** [zendesk/rate_my_app_android#11]
### Description
* Is there a way to style the dialog (like in the original Zendesk SDK)
 
### Device information
* Android OS version: 8.0.0
* Compile SDK version: 1.11.0.1
* Build tools version: 27.0.3
* Any other relevant information: 
I had a couple of styles defined in the `app_theme` style: `RateMyAppButtonStyle`, `RateMyAppTitleStyle` and `RateMyAppDividerStyle`. It looks like these have been removed in this sdk. Can they be added back, so the dialog can look the way I'd like it to?

**Comment by eepDev** [comment]
Hi @ahabbaba9,

Styles are still there, only renamed. See https://github.com/zendesk/rate_my_app_android/blob/master/ratemyapp/src/main/res/values/styles.xml#L5.

`RateMyAppButtonStyle` -> `rma_button`
`RateMyAppTitleStyle` -> `rma_title`
`RateMyAppDividerStyle` -> `rma_divider`

Sorry for the inconvenience caused,
Elvis
